
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tubuyaki_app_development


  
test:
  <<: *default
  database: tubuyaki_app_test


production:
  <<: *default
  database: tubuyaki_app_production
  username: tubuyaki_app
  password: <%= ENV['TUBUYAKI_APP_DATABASE_PASSWORD'] %>
